name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Configure Git commiter info
        run: |
          git config --global user.email "`git --no-pager show -s --format='%ae' HEAD`"
          git config --global user.name "`git --no-pager show -s --format='%an' HEAD`"

      - name: Build
        run: |
          gatsby build --prefix-path
          cp -r .github public/.github

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
